### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by yKsenomorf** [depressionclient/issues#4]
`AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80004005
17:48:16.456 [Thread-6] ERROR za1qv - Error in class 'LibraryLWJGLOpenAL'
17:48:16.458 [Thread-6] ERROR za1qv - Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
Exception in thread "Client thread" java.lang.NullPointerException
	at uy5sv.mc3wv(Unknown Source)
	at fam0i.jsjo6(Unknown Source)
	at fam0i.kdczk(Unknown Source)
	at z87tq.egrww(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)`

**Comment by Mat1337** [comment]
yes I am aware of the issue it is due to a discord library messing up, working on a fix.
